pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                script {
                    def rootDir = "backend/mock-service-v1"
                    echo "Changing directory to: ${rootDir}"
                    dir(rootDir) {
                        sh "ls -la"
                        def mvnCmd = 'mvn clean package'
                        def mvnOutput = sh(script: mvnCmd, returnStdout: true).trim()
                        if (mvnOutput.contains('BUILD SUCCESS')) {
                            echo 'Maven build successful'
                        } else {
                            error 'Maven build failed'
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                withCredentials(bindings: [ string(credentialsId: 'k8s-cluster-token', variable: 'api_token') ]) {
                    sh 'kubectl apply -f backend/mock-service-v1/k8s.yaml --server https://59c9-2800-200-ed50-2d5-f94d-c6d4-a11f-1684.ngrok-free.app --token $api_token --insecure-skip-tls-verify=true'
                }
            }
        }
    }
}
